formulario/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import (carta_intencao_views, conjuge_familia_views,
                    dados_adicionais_views, dados_bancarios_views,
                    dados_candidato_views, email_redes_sociais_views,
                    emprego_views, enderecos_views, ensino_views,
                    enviar_formulario_views, experiencia_seguranca_views,
                    familiares_views, habilitacao_motorista_views,
                    hobbies_clube_views, informacao_candidato_views,
                    inquerito_views, parente_policial_amigos_views,
                    patrimonio_veiculo_views, protestos_dividas_views,
                    servico_militar_views)

app_name = "formulario"

urlpatterns = [
    path(
        "formulario_dados_adicionais/",
        dados_adicionais_views.formulario_dados_adicionais,
        name="formulario_dados_adicionais",
    ),
    path(
        "formulario_dados_adicionais/enviado/",
        dados_adicionais_views.formulario_dados_adicionais_enviado,
        name="formulario_dados_adicionais_enviado",
    ),
    path("get_cidades/", dados_adicionais_views.get_cidades, name="get_cidades"),
    path(
        "formulario_email_redes_sociais/",
        email_redes_sociais_views.formulario_email_redes_sociais,
        name="formulario_email_redes_sociais",
    ),
    path(
        "formulario_email_redes_sociais/enviado/",
        email_redes_sociais_views.formulario_email_redes_sociais_enviado,
        name="formulario_email_redes_sociais_enviado",
    ),
    path(
        "formulario_dados_bancarios/",
        dados_bancarios_views.dados_bancarios,
        name="formulario_dados_bancarios",
    ),
    path(
        "formulario_dados_bancarios/enviado/",
        dados_bancarios_views.dados_bancarios_enviado,
        name="formulario_dados_bancarios_enviado",
    ),
    path(
        "formulario_informacao_candidato/",
        informacao_candidato_views.informacao_candidato,
        name="formulario_informacao_candidato",
    ),
    path(
        "formulario_informacao_candidato/enviado/",
        informacao_candidato_views.informacao_candidato_enviado,
        name="formulario_informacao_candidato_enviado",
    ),
    path("lista/", dados_candidato_views.lista, name="inlineform_lista"),
    path(
        "formulario_dados_candidato/<int:candidato_id>/",
        dados_candidato_views.dados_candidato,
        name="formulario_dados_candidato",
    ),
    path(
        "formulario_dados_candidato_enviado/<int:candidato_id>/",
        dados_candidato_views.dados_candidato_eviado,
        name="formulario_dados_candidato_enviado",
    ),
    path(
        "formulario_familiares/<int:candidato_id>/",
        familiares_views.familiares,
        name="formulario_familiares",
    ),
    path(
        "formulario_familiares_enviado/<int:candidato_id>/",
        familiares_views.familiares_enviado,
        name="formulario_familiares_enviado",
    ),
    path(
        "formulario_conjuge_familia/",
        conjuge_familia_views.conjuge_familia,
        name="formulario_conjuge_familia",
    ),
    path(
        "formulario_conjuge_familia/enviado/",
        conjuge_familia_views.conjuge_familia_enviado,
        name="formulario_conjuge_familia_enviado",
    ),
    path(
        "formulario_parente_policial_amigos/<int:candidato_id>/",
        parente_policial_amigos_views.parente_policial_amigos,
        name="formulario_parente_policial_amigos",
    ),
    path(
        "formulario_parente_policial_amigos/enviado/<int:candidato_id>/",
        parente_policial_amigos_views.parente_policial_amigos_enviado,
        name="formulario_parente_policial_amigos_enviado",
    ),
    path(
        "formulario_hobbies_clube/<int:candidato_id>/",
        hobbies_clube_views.hobbies_clube,
        name="formulario_hobbies_clube",
    ),
    path(
        "formulario_hobbies_clube/enviado/<int:candidato_id>/",
        hobbies_clube_views.hobbies_clube_enviado,
        name="formulario_hobbies_clube_enviado",
    ),
    path(
        "formulario_inquerito/<int:candidato_id>/",
        inquerito_views.inquerito,
        name="formulario_inquerito",
    ),
    path(
        "formulario_inquerito/enviado/<int:candidato_id>/",
        inquerito_views.inquerito_enviado,
        name="formulario_inquerito_enviado",
    ),
    path(
        "formulario_emprego/<int:candidato_id>/",
        emprego_views.emprego,
        name="formulario_emprego",
    ),
    path(
        "formulario_emprego/enviado/<int:candidato_id>/",
        emprego_views.emprego_enviado,
        name="formulario_emprego_enviado",
    ),
    path(
        "formulario_experiencia_seguranca/<int:candidato_id>/",
        experiencia_seguranca_views.experiencia_seguranca,
        name="formulario_experiencia_seguranca",
    ),
    path(
        "formulario_experiencia_seguranca/enviado/<int:candidato_id>/",
        experiencia_seguranca_views.experiencia_seguranca_enviado,
        name="formulario_experiencia_seguranca_enviado",
    ),
    path(
        "formulario_servico_militar/<int:candidato_id>/",
        servico_militar_views.servico_militar,
        name="formulario_servico_militar",
    ),
    path(
        "formulario_servico_militar/enviado/<int:candidato_id>/",
        servico_militar_views.servico_militar_enviado,
        name="formulario_servico_militar_enviado",
    ),
    path(
        "formulario_enderecos/<int:candidato_id>/",
        enderecos_views.enderecos,
        name="formulario_enderecos",
    ),
    path(
        "formulario_enderecos/enviado/<int:candidato_id>/",
        enderecos_views.enderecos_enviado,
        name="formulario_enderecos_enviado",
    ),
    path(
        "formulario_ensino/<int:candidato_id>/",
        ensino_views.ensino,
        name="formulario_ensino",
    ),
    path(
        "formulario_ensino/enviado/<int:candidato_id>/",
        ensino_views.ensino_enviado,
        name="formulario_ensino_enviado",
    ),
    path(
        "formulario_habilitacao_motorista/<int:candidato_id>/",
        habilitacao_motorista_views.habilitacao_motorista,
        name="formulario_habilitacao_motorista",
    ),
    path(
        "formulario_habilitacao_motorista/enviado/<int:candidato_id>/",
        habilitacao_motorista_views.habilitacao_motorista_enviado,
        name="formulario_habilitacao_motorista_enviado",
    ),
    path(
        "formulario_protestos_dividas/<int:candidato_id>/",
        protestos_dividas_views.protestos_dividas,
        name="formulario_protestos_dividas",
    ),
    path(
        "formulario_protestos_dividas/enviado/<int:candidato_id>/",
        protestos_dividas_views.protestos_dividas_enviado,
        name="formulario_protestos_dividas_enviado",
    ),
    path(
        "formulario_patrimonio_veiculo/<int:candidato_id>/",
        patrimonio_veiculo_views.patrimonio_veiculo,
        name="formulario_patrimonio_veiculo",
    ),
    path(
        "formulario_patrimonio_veiculo/enviado/<int:candidato_id>/",
        patrimonio_veiculo_views.patrimonio_veiculo_enviado,
        name="formulario_patrimonio_veiculo_enviado",
    ),
    path(
        "formulario_carta_intencao/<int:candidato_id>/",
        carta_intencao_views.carta_intencao,
        name="formulario_carta_intencao",
    ),
    path(
        "formulario_carta_intencao/enviado/<int:candidato_id>/",
        carta_intencao_views.carta_intencao_enviado,
        name="formulario_carta_intencao_enviado",
    ),
    path(
        "formulario_enviado/<int:candidato_id>/",
        enviar_formulario_views.enviar_formulario,
        name="formulario_enviado",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projeto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("usuarios.urls")),
    path("", include("formulario.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

formulario/views.py
# from django.contrib.auth import login
from audioop import reverse

from django.contrib import messages
from django.contrib.auth.decorators import login_required

# from django.core.paginator import Paginator
from django.http import Http404, JsonResponse

# from django.http import HttpResponse
from django.shortcuts import redirect, render

from formulario.forms.dados_candidato_forms import DadosCandidatoForm
from formulario.forms.email_candidato_forms import EmailCandidatoForm
from utils.cidades_estado import obter_cidades_do_estado

from .models.dados_candidato_models import DadosCandidato
from .models.email_candidato_models import EmailCandidato


@login_required(login_url="/login")
def formulario(request):
    if request.method == "GET":
        dados = DadosCandidato.objects.filter(user=request.user).first()

        if not dados:
            form = DadosCandidatoForm()
        else:
            form = DadosCandidatoForm(instance=dados)

        return render(
            request,
            "formulario.html",
            {
                "form": form,
            },
        )


@login_required(login_url="/login")
def formulario_enviado(request):
    if request.method == "POST":
        user = request.user
        dados, created = DadosCandidato.objects.get_or_create(user=user)
        form = DadosCandidatoForm(data=request.POST, instance=dados)

        if form.is_valid():
            form.save()
            return redirect("formulario:formulario_email")
        else:
            return render(
                request,
                "formulario.html",
                {
                    "form": form,
                },
            )
    else:
        raise Http404()


@login_required(login_url="/login")
def formulario_email(request):
    if request.method == "GET":
        dados = EmailCandidato.objects.filter(user=request.user).first()

        if not dados:
            form = EmailCandidatoForm()
        else:
            form = EmailCandidatoForm(instance=dados)

        return render(
            request,
            "formulario_email.html",
            {
                "form": form,
            },
        )


@login_required(login_url="/login")
def formulario_email_enviado(request):
    if request.method == "POST":
        user = request.user
        dados, created = EmailCandidato.objects.get_or_create(user=user)
        form = EmailCandidatoForm(data=request.POST, instance=dados)

        if form.is_valid():
            form.save()
            return redirect("formulario:formulario_email")
        else:
            return render(
                request,
                "formulario_email.html",
                {
                    "form": form,
                },
            )
    else:
        raise Http404()


def get_cidades(request):
    estado = request.GET.get("estado")
    cidades = obter_cidades_do_estado(estado)  # Implemente essa função
    return JsonResponse({"cidades": cidades})

formulario/views/carta_intencao_views.py
from django.contrib.auth.decorators import login_required
from django.forms import inlineformset_factory
from django.http import JsonResponse
from django.shortcuts import redirect, render
# Create your views here.
from django.urls import reverse
from django.views.generic import CreateView

from formulario.forms import (CartaIntencaoForm, EmpregoForm, EnderecosForm,
                              PassagemForm, PrestacaoDividaForm,
                              ProtestosDividasForm)
from formulario.models import (Candidato, Dados, Emprego, Enderecos,
                               Pagination, Passagem, PrestacaoDivida)


@login_required(login_url="/login")
def carta_intencao(request, candidato_id):
    if request.method == "GET":
        to_page = Candidato.objects.filter(user=request.user).first()
        objeto = Dados.objects.filter(id=candidato_id, user=request.user).first()

        pagination = Pagination.objects.filter(user=request.user).first()
        for (field_name) in pagination._meta.fields:  # Itera pelos campos do objeto Pagination
            field_value = getattr(pagination, field_name.attname)
            if field_value == "active":
                setattr(pagination, field_name.attname, "used")
        pagination.page_19 = "active"
        pagination.save()
    
        form_carta_intencao = CartaIntencaoForm(instance=objeto)      

        context = {
            "form_carta_intencao": form_carta_intencao,
            "pagination": pagination,
            "to_page": to_page,
            "objeto": objeto,
        }
        return render(request, "carta_intencao.html", context)
    

    
@login_required(login_url="/login")
def carta_intencao_enviado(request, candidato_id):
    if request.method == "POST":
        pagination = Pagination.objects.filter(user=request.user).first()
        to_page = Candidato.objects.filter(user=request.user).first()
        objeto = Dados.objects.filter(id=candidato_id).first()

        form_carta_intencao = CartaIntencaoForm(request.POST, instance=objeto)

        if form_carta_intencao.is_valid():
            form_carta_intencao.save()
            pagination.page_19 = "used"
            pagination.page_20 = "used"
            pagination.save()
            return redirect("formulario:formulario_enviado", objeto.id)
        else:            
            pagination.page_19 = "active"
            pagination.save()
            return render(request, "carta_intencao.html", locals())

formulario/views/conjuge_familia_views.py
# from django.contrib.auth import login
from audioop import reverse

from django.contrib import messages
from django.contrib.auth.decorators import login_required
# from django.core.paginator import Paginator
from django.http import Http404, JsonResponse
# from django.http import HttpResponse
from django.shortcuts import redirect, render

from formulario.forms import ConjugeFamiliaForm
from formulario.models import Candidato, Dados, Pagination
from utils.cidades_estado import obter_cidades_do_estado


@login_required(login_url="/login")
def conjuge_familia(request):
    if request.method == "GET":
        to_page = Candidato.objects.filter(user=request.user).first()
        objeto = Dados.objects.filter(user=request.user).first()
        pagination = Pagination.objects.filter(user=request.user).first()

        for (
            field_name
        ) in pagination._meta.fields:  # Itera pelos campos do objeto Pagination
            field_value = getattr(pagination, field_name.attname)
            if field_value == "active":
                setattr(pagination, field_name.attname, "used")
        pagination.page_7 = "active"
        pagination.save()

        if not objeto:
            form = ConjugeFamiliaForm()
        else:
            form = ConjugeFamiliaForm(instance=objeto)
        return render(
            request,
            "conjuge_familia.html",
            {
                "form": form,
                "pagination": pagination,
                "objeto": objeto,
                "to_page": to_page,
            },
        )


@login_required(login_url="/login")
def conjuge_familia_enviado(request):
    if request.method == "POST":
        to_page = Candidato.objects.filter(user=request.user).first()
        objeto = Dados.objects.filter(user=request.user).first()
        form = ConjugeFamiliaForm(data=request.POST, instance=objeto)
        pagination = Pagination.objects.filter(user=request.user).first()

        if form.is_valid():
            form.save()
            pagination.page_7 = "used"
            pagination.page_8 = "used"
            pagination.save()
            #objeto = Dados.objects.filter(user=request.user).first()
            return redirect("formulario:formulario_parente_policial_amigos", objeto.id)

        else:
            pagination.page_7 = "active"
            pagination.save()
            return render(
                request,
                "conjuge_familia.html",
                locals()
            )
    else:
        raise Http404()

formulario/views/enviar_formulario_views.py
import random

from django.contrib.auth.decorators import login_required
from django.forms import inlineformset_factory
from django.http import JsonResponse
from django.shortcuts import redirect, render
# Create your views here.
from django.urls import reverse
from django.views.generic import CreateView
from datetime import date
from formulario.models import Dados


# Função para gerar um número de protocolo aleatório
def gerar_numero_protocolo():
    # Gere um número aleatório de 6 dígitos
    numero = random.randint(100000, 999999)
    return str(numero)

# Use a função para gerar um número de protocolo


@login_required(login_url="/login")
def enviar_formulario(request, candidato_id):
    if request.method == "GET":
        objeto = Dados.objects.filter(id=candidato_id).first()
        if not objeto.numero_protocolo:
            num_protocolo = gerar_numero_protocolo()
            objeto.data_protocolo = date.today()
            objeto.numero_protocolo = num_protocolo
            objeto.save()
        context = {'objeto': objeto}  # Crie um dicionário com as variáveis de contexto
        return render(request, "enviar_formulario.html", context)

formulario/templates/dados_adicionais.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block title %} Formulário {% endblock %}

{% block content %}
<style>
    #id_data_nasc_candidato {
        padding: 6px 12px; 
    }
    #calendar_icon {
        position: absolute;
        right: 130px;
        top: 50%;
        transform: translateY(-50%);
        border: none; /* Remove a borda do input */
        box-shadow: none; 
        background: transparent;
        pointer-events: none; /* Torna o elemento não interativo */
    }
</style>

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h1 style="font-size:190%">Dados Adicionais do Candidato</h1>
                
                <form action="{% url 'formulario:formulario_dados_adicionais_enviado' %}" method="POST">
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="input-group col-md-6">
                            <label for="{{ field.id_for_label }}">{{ field.label }}
                                {% if field.field.required %}
                                    <b style="color: #FF0000; text-decoration: none; font-size: 18px;" href="#" title="Este campo é obrigatório" data-toggle="tooltip">*</b>
                                {% endif %}
                            </label>
                            {% if field.name == "data_nasc_candidato" %}
                                <div class="input-group mb-3">
                                    {{ field }}
                                    <span class="input-group-text" id="calendar_icon"><i class="fa-regular fa-calendar"></i></span><span class="input-group-text" id="basic-addon2">{{ field.help_text }}</span>
                                </div>
                            {% else %}
                                <div class="input-group mb-3">
                                    {{ field }}
                                </div>
                            {% endif %}  
                    
                            {{ field.errors }}
                           
                              
                        </div>                        
                    {% endfor %}
                       
                    <div style="margin-top: 20px; display: flex; justify-content: space-between; margin-bottom: 35px;">
                        <input type="button" class="btn btn-secondary btn-block" value="Anterior" style="flex: .4; margin-right: 5px" onclick="irParaFormulario()">
                        <input type="submit" class="btn btn-primary btn-block" value="Próximo" style="flex: .4;margin-left: 5px">
                    </div>

                </form>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function () {
            $('.datepicker').datepicker({
                format: 'dd/mm/yyyy',
                language : 'pt-BR'
                
            });
            
            {% comment %} $('#id_data_nasc_candidato').datepicker({
                'language' : 'pt-BR',
            }); {% endcomment %}

            $("#uf_natural").change(function () {
                var estado = $(this).val();
                $.ajax({
                    url: "{% url 'formulario:get_cidades' %}",
                    data: {estado: estado},
                    dataType: "json",
                    success: function (data) {
                        var options = "<option value=''>Selecione a cidade</option>";
                        data.cidades.forEach(function (cidade) {
                            options += "<option value='" + cidade + "'>" + cidade + "</option>";
                        });
                        $("#natural").html(options);
                    }
                });
            });
        });
    
        function irParaFormulario() {
            window.location.href = "{% url 'formulario:formulario_dados_candidato' to_page.id %}";
        }       

      </script>

      
{% endblock %}

formulario/templates/dados_candidato.html
{% extends 'base.html' %}

{% block title %} Formulário {% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h1 style="font-size:190%">Dados do Candidato</h1>   
                <form action="{% url 'formulario:formulario_dados_candidato_enviado' to_page.id %}" method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="input-group col-md-6">
                            <label for="{{ field.id_for_label }}">{{ field.label }}
                                {% if field.field.required %}
                                    <b style="color: #FF0000; text-decoration: none; font-size: 18px;" href="#" title="Este campo é obrigatório" data-toggle="tooltip">*</b>
                                {% endif %}
                            </label>
                            <div class="input-group mb-3">
                                {{field}}
                            </div>
                            {% if field.help_text %}
                                <p class="help-text">{{ field.help_text }}</p>
                            {% endif %}
                            {{ field.errors }}  
                        </div>                        
                    {% endfor %}
                    {{ form_telefone.management_form }}
                    <div class="errorlist">
                        {% if form_telefone.errors %}
                            {% for error in form_telefone.errors %}
                                {% if forloop.first %}
                                    {{ error }}
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                    </div>
                    <table class="table">
                        {% for ft in form_telefone %}                        
                                {% if forloop.first %}
                                    <tr> 
                                        {% for f in ft.visible_fields %}
                                            <th>{{ f.label }} 
                                            </th>
                                        {%endfor%}
                                    </tr>
                                {% endif %}
                                <tr class="inlineform"> 
                                    {% for f in ft.hidden_fields %}
                                        {{ f }}
                                    {%endfor%} 
                                    {% for f in ft.visible_fields %}
                                        <td>{{ f }}</td>
                                    {%endfor%}                                
                                </tr>
                        {%endfor%}                        
                    </table>
                    <div style="margin-top: 20px; display: flex; justify-content: space-between; margin-bottom: 35px;">
                        <input type="button" class="btn btn-secondary btn-block" value="Anterior" style="flex: .4; margin-right: 5px" onclick="irParaFormulario()">
                        <input type="submit" class="btn btn-primary btn-block" value="Próximo" style="flex: .4;margin-left: 5px">
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

{% block scripts %}
    <script type="text/javascript">
        $(function() {
            $('.inlineform').formset({
                prefix: '{{ form_telefone.prefix }}',
                addText: "Adicionar novo Telefone",
                deleteText: "Remover",
                deleteCssClass: 'btn btn-danger',
                addCssClass: 'btn btn-primary',                
            });
        })
    </script>
    <script>
        $(document).ready(function () {
            $("#uf_natural").change(function () {
                var estado = $(this).val();
                $.ajax({
                    url: "{% url 'formulario:get_cidades' %}",
                    data: {estado: estado},
                    dataType: "json",
                    success: function (data) {
                        var options = "<option value=''>Selecione a cidade</option>";
                        data.cidades.forEach(function (cidade) {
                            options += "<option value='" + cidade + "'>" + cidade + "</option>";
                        });
                        $("#natural").html(options);
                    }
                });
            });
        });
    </script>
    <script>
        function irParaFormulario() {
            window.location.href = "/formulario_informacao_candidato";
        }
    </script>
{% endblock scripts %}

formulario/templates/enderecos.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block title %} Formulário {% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-10">
            
                <form action="{% url 'formulario:formulario_enderecos_enviado' objeto.id %}" method="POST">
                    {% csrf_token %}

                    <div class="row justify-content-center">
                        <div class="col-md-6"> 
                            <h1 style="font-size:190%">Endereços</h1>
                            <p>Declarar em ordem cronológica todos os lugares onde residiu e reside, a partir dos 10 anos de idade:</p>
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col-md-6"> <!-- Aumentei a largura da coluna para que a tabela seja mais ampla -->
                            {{ form_enderecos.management_form }}
                            <div class="errorlist">
                                {% if form_enderecos.errors %}
                                    {% for error in form_enderecos.errors %}
                                        {% if forloop.first %}
                                            {{ error }}
                                        {% endif %}
                                    {% endfor %}
                                {% endif %}
                            </div>

                            <table class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th colspan="2" class="text-center">
                                            <b style="font-size: 30px;">Endereços</b>
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for field in form_enderecos %}
                                    <tr class="inlineform">
                                        <td> <!-- A segunda coluna ocupa o espaço restante -->
                                            {% for f in field.visible_fields %} 
                                                <div class="mb-3">
                                                    <b>{{ f.label }}: </b>
                                                    {% if field.field.required %}
                                                    <b style="color: #FF0000; font-size: 18px;" href="#" title="Este campo é obrigatório" data-toggle="tooltip">*</b>
                                                    {% endif %}
                                                    {% if f.name == "idade_inicio" or f.name == "idade_fim" %}
                                                        <div class="input-group mb-3">
                                                            {{ f }}
                                                            <span class="input-group-text" id="basic-addon2">{{ f.help_text }}</span>
                                                        </div>
                                                    {% else %}
                                                        {{ f }}
                                                    {% endif %}
                                                </div> 
                                                {% for f in field.hidden_fields %}    
                                                {{ f }}
                                                {% endfor %}  
                                            {% endfor %}  
                                        </td>
                                    </tr>        
                                    {% endfor %}   
                                </tbody>
                            </table>  
                        </div>  
                    </div>          
                         
                    <div class="row justify-content-center" >
                        <div class="col-md-5">
                            <div style="margin-top: 20px; display: flex; justify-content: space-between; margin-bottom: 90px;">
                                <input type="button" class="btn btn-secondary btn-block" value="Anterior" style="flex: .4; margin-right: 5px" onclick="irParaFormulario()">
                                <input type="submit" class="btn btn-primary btn-block" value="Próximo" style="flex: .4;margin-left: 5px">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock content %}

{% block scripts %}
    <script type="text/javascript">
        $(document).ready(function () {
            $('.inlineform').formset({
                prefix: '{{ form_enderecos.prefix }}',
                addText: "Adicionar novo Endereço",
                deleteText: "Remover",      
                deleteCssClass: 'btn btn-danger',
                addCssClass: 'btn btn-primary',          
            });   
            $('.datepicker').datepicker({
                format: 'dd/mm/yyyy',
                language : 'pt-BR'
            }); 
        });
    </script>
    

    <script>
        function irParaFormulario() {
            window.location.href = "{% url 'formulario:formulario_servico_militar' objeto.id %}";
        }
    </script>

{% endblock scripts %}